# arxivの学問領域の指定
subject: 'cat:cs.*'

# 検索キーワード
keywords:
        robot: 3
        manipulation: 3
        reinforcement learning: 3
        skill acquisition: 3
        object-centric: 3
        imitation learning: 3
        world model: 3

# 通知の閾値
score_threshold: 0
